services:
  webapp:
    container_name: obscreen
    restart: unless-stopped
    image: jierka/obscreen:latest
    environment:
      - DEMO=false
      - DEBUG=false
      - SECRET_KEY=ANY_SECRET_KEY_HERE
      - PORT=5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/db:/app/data/db
      - ./data/uploads:/app/data/uploads
      - ./var/run/storage:/app/var/run/storage
    ports:
      - 5000:5000
